# Generated by Django 3.2.8 on 2021-12-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_schooluser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_name',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
