# Generated by Django 3.2.8 on 2021-12-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_schooluser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooluser',
            old_name='user_name',
            new_name='username',
        ),
    ]
